apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- printf "%s-%s" .Release.Name "configmap" | trunc 63 | trimSuffix "-" -}}
  labels:
    app: {{ template "drkiq.name" . }}
    chart: {{ template "drkiq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.data }}
  {{ $key }}: {{ $value | replace "<local>" $.Release.Namespace | quote }}
{{- end }}
