apiVersion: v1
appVersion: "1.0"
description: Ruby on Rails example app
name: drkiq
version: 0.1.0
sources:
  - https://github.com/a114m/railsapp-kubernetes-example
maintainers:
  - name: allam
    email: m@allam.cc
