apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rails.unicornFullname" . }}
  labels:
    app: {{ template "rails.unicornName" . }}
    chart: {{ template "rails.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.unicorn.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rails.unicornName" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rails.unicornName" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "rails.unicornName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- if .Values.unicorn.health }}
          livenessProbe:
            httpGet:
              path: {{ .Values.unicorn.health.livenessProbe.path }}
              port: http
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: {{ .Values.unicorn.health.readinessProbe.path }}
              port: http
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          {{- end }}
          resources:
{{ toYaml .Values.unicorn.resources | indent 12 }}
          env:
{{ include "rails.env" . | indent 12 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
    {{- with .Values.unicorn.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.unicorn.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.unicorn.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.unicorn.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.unicorn.rollingUpdate.maxUnavailable }}
